// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service/sys.proto

package service

import (
	protos "github.com/actfuns/pitaya/v2/protos"
	_ "github.com/actfuns/pitaya/v2/protos/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_sys_proto protoreflect.FileDescriptor

const file_service_sys_proto_rawDesc = "" +
	"\n" +
	"\x11service/sys.proto\x12\x0eprotos.service\x1a\x0eresponse.proto\x1a\n" +
	"kick.proto\x1a\rsession.proto\x1a\x15api/annotations.proto2\xb7\x01\n" +
	"\x03Sys\x128\n" +
	"\vBindSession\x12\x0f.protos.Session\x1a\x10.protos.Response\"\x06\x8a\xb5\x18\x02\b\x01\x128\n" +
	"\vPushSession\x12\x0f.protos.Session\x1a\x10.protos.Response\"\x06\x8a\xb5\x18\x02\b\x01\x123\n" +
	"\x04Kick\x12\x0f.protos.KickMsg\x1a\x12.protos.KickAnswer\"\x06\x8a\xb5\x18\x02\b\x01\x1a\a\x82\xb5\x18\x03sysB-Z+github.com/actfuns/pitaya/v2/protos/serviceb\x06proto3"

var file_service_sys_proto_goTypes = []any{
	(*protos.Session)(nil),    // 0: protos.Session
	(*protos.KickMsg)(nil),    // 1: protos.KickMsg
	(*protos.Response)(nil),   // 2: protos.Response
	(*protos.KickAnswer)(nil), // 3: protos.KickAnswer
}
var file_service_sys_proto_depIdxs = []int32{
	0, // 0: protos.service.Sys.BindSession:input_type -> protos.Session
	0, // 1: protos.service.Sys.PushSession:input_type -> protos.Session
	1, // 2: protos.service.Sys.Kick:input_type -> protos.KickMsg
	2, // 3: protos.service.Sys.BindSession:output_type -> protos.Response
	2, // 4: protos.service.Sys.PushSession:output_type -> protos.Response
	3, // 5: protos.service.Sys.Kick:output_type -> protos.KickAnswer
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_sys_proto_init() }
func file_service_sys_proto_init() {
	if File_service_sys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_sys_proto_rawDesc), len(file_service_sys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_sys_proto_goTypes,
		DependencyIndexes: file_service_sys_proto_depIdxs,
	}.Build()
	File_service_sys_proto = out.File
	file_service_sys_proto_goTypes = nil
	file_service_sys_proto_depIdxs = nil
}
