// Code generated by protoc-gen-pitaya-prpc. DO NOT EDIT.
// versions:
// - protoc-gen-pitaya-prpc v0.1.0
// - protoc             v6.31.1
// source: service/sys.proto

package service

import (
	context "context"

	component "github.com/actfuns/pitaya/v2/component"
	protos "github.com/actfuns/pitaya/v2/protos"
	prpc "github.com/actfuns/pitaya/v2/prpc"
)

const (
	PRPC_Sys_BindSession_FullMethodName = "/protos.service.Sys/BindSession"
	PRPC_Sys_PushSession_FullMethodName = "/protos.service.Sys/PushSession"
	PRPC_Sys_Kick_FullMethodName        = "/protos.service.Sys/Kick"
)

// SysPrpcClient is the client API for Sys service.
type SysPrpcClient interface {
	BindSession(ctx context.Context, in *protos.Session, opts ...prpc.CallOption) (*protos.Response, error)
	PushSession(ctx context.Context, in *protos.Session, opts ...prpc.CallOption) (*protos.Response, error)
	Kick(ctx context.Context, in *protos.KickMsg, opts ...prpc.CallOption) (*protos.KickAnswer, error)
}

type sysPrpcClient struct {
	app prpc.Client
}

func NewSysPrpcClient(app prpc.Client) SysPrpcClient {
	return &sysPrpcClient{app: app}
}

func (c *sysPrpcClient) BindSession(ctx context.Context, in *protos.Session, opts ...prpc.CallOption) (*protos.Response, error) {
	out := new(protos.Response)
	err := c.app.RPC(ctx, "sys.sys.bindSession", out, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysPrpcClient) PushSession(ctx context.Context, in *protos.Session, opts ...prpc.CallOption) (*protos.Response, error) {
	out := new(protos.Response)
	err := c.app.RPC(ctx, "sys.sys.pushSession", out, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysPrpcClient) Kick(ctx context.Context, in *protos.KickMsg, opts ...prpc.CallOption) (*protos.KickAnswer, error) {
	out := new(protos.KickAnswer)
	err := c.app.RPC(ctx, "sys.sys.kick", out, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysPrpcServer is the server API for Sys service.
// All implementations must embed UnimplementedSysPrpcServer
// for forward compatibility.
type SysPrpcServer interface {
	component.Component
	BindSession(context.Context, *protos.Session) (*protos.Response, error)
	PushSession(context.Context, *protos.Session) (*protos.Response, error)
	Kick(context.Context, *protos.KickMsg) (*protos.KickAnswer, error)
}

// UnimplementedSysPrpcServer must be embedded to have
// forward compatible implementations.
type UnimplementedSysPrpcServer struct {
	component.Base
}

func (UnimplementedSysPrpcServer) BindSession(context.Context, *protos.Session) (*protos.Response, error) {
	return nil, nil
}
func (UnimplementedSysPrpcServer) PushSession(context.Context, *protos.Session) (*protos.Response, error) {
	return nil, nil
}
func (UnimplementedSysPrpcServer) Kick(context.Context, *protos.KickMsg) (*protos.KickAnswer, error) {
	return nil, nil
}

func _PRPC_Sys_BindSession_Handler(srv interface{}, ctx context.Context, dec func(ctx context.Context, arg interface{}) (context.Context, interface{}, error)) (interface{}, error) {
	in := new(protos.Session)
	ctx, result, err := dec(ctx, in)
	if err != nil {
		return nil, err
	}
	return srv.(SysPrpcServer).BindSession(ctx, result.(*protos.Session))
}
func _PRPC_Sys_PushSession_Handler(srv interface{}, ctx context.Context, dec func(ctx context.Context, arg interface{}) (context.Context, interface{}, error)) (interface{}, error) {
	in := new(protos.Session)
	ctx, result, err := dec(ctx, in)
	if err != nil {
		return nil, err
	}
	return srv.(SysPrpcServer).PushSession(ctx, result.(*protos.Session))
}
func _PRPC_Sys_Kick_Handler(srv interface{}, ctx context.Context, dec func(ctx context.Context, arg interface{}) (context.Context, interface{}, error)) (interface{}, error) {
	in := new(protos.KickMsg)
	ctx, result, err := dec(ctx, in)
	if err != nil {
		return nil, err
	}
	return srv.(SysPrpcServer).Kick(ctx, result.(*protos.KickMsg))
}

// PRPC_Sys_ServiceDesc is the prpc.ServiceDesc for Sys service.
var PRPC_Sys_ServiceDesc = &prpc.ServiceDesc{
	DomainName:  "sys",
	ServiceName: "sys",
	Methods: []prpc.MethodDesc{
		{
			MethodName: "bindSession",
			Handler:    _PRPC_Sys_BindSession_Handler,
			Client:     false,
			Reentrant:  true,
		},
		{
			MethodName: "pushSession",
			Handler:    _PRPC_Sys_PushSession_Handler,
			Client:     false,
			Reentrant:  true,
		},
		{
			MethodName: "kick",
			Handler:    _PRPC_Sys_Kick_Handler,
			Client:     false,
			Reentrant:  true,
		},
	},
}

func RegisterSysPrpcServer(s prpc.ServiceRegistrar, srv SysPrpcServer) {
	s.Register(PRPC_Sys_ServiceDesc, srv)
}
