// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/annotations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Method describes the behavioral flags of a method.
// It combines reentrant and client options into a single extension.
type Method struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reentrant marks a method as reentrant (Orleans-style).
	// When true, the method can be executed concurrently without blocking
	// the actor serial queue (e.g., for DB I/O operations).
	// Default: false.
	Reentrant bool `protobuf:"varint,1,opt,name=reentrant,proto3" json:"reentrant,omitempty"`
	// client marks a method as a client-facing handler.
	// When true, the method is registered in both the remote service (for RPC)
	// and the handler service (for direct client connections via WebSocket/TCP).
	// Default: false (only accessible via RPC).
	Client bool `protobuf:"varint,2,opt,name=client,proto3" json:"client,omitempty"`
	// codec enables UnmarshalXxx / MarshalXxx hooks for this method.
	// When true, generated code adds UnmarshalXxx and MarshalXxx methods
	// to the server interface and calls them in the handler.
	// This allows custom byte-level processing before unmarshal and after marshal.
	// Default: false.
	Codec         bool `protobuf:"varint,3,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Method) Reset() {
	*x = Method{}
	mi := &file_api_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method) ProtoMessage() {}

func (x *Method) ProtoReflect() protoreflect.Message {
	mi := &file_api_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method.ProtoReflect.Descriptor instead.
func (*Method) Descriptor() ([]byte, []int) {
	return file_api_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Method) GetReentrant() bool {
	if x != nil {
		return x.Reentrant
	}
	return false
}

func (x *Method) GetClient() bool {
	if x != nil {
		return x.Client
	}
	return false
}

func (x *Method) GetCodec() bool {
	if x != nil {
		return x.Codec
	}
	return false
}

var file_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "pitaya.domain",
		Tag:           "bytes,50000,opt,name=domain",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Method)(nil),
		Field:         50001,
		Name:          "pitaya.method",
		Tag:           "bytes,50001,opt,name=method",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "pitaya.errors",
		Tag:           "varint,50003,opt,name=errors",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50005,
		Name:          "pitaya.error_level",
		Tag:           "varint,50005,opt,name=error_level",
		Filename:      "api/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// domain specifies the server type for routing (e.g. "room", "game").
	// Used by protoc-gen-pitaya-prpc to determine the target server type.
	// Usage:
	//
	//	service Room {
	//	  option (pitaya.domain) = "room";
	//	  rpc Join(JoinReq) returns (JoinResp);
	//	}
	//
	// optional string domain = 50000;
	E_Domain = &file_api_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// method specifies the behavioral flags of a method,
	// including reentrant, client, and codec options.
	// Usage:
	//
	//	rpc Query(QueryReq) returns (QueryResp) {
	//	  option (pitaya.method) = { reentrant: true, client: true, codec: true };
	//	}
	//	rpc Join(JoinReq) returns (JoinResp) {
	//	  option (pitaya.method) = { client: true };
	//	}
	//	rpc Kick(KickMsg) returns (KickAnswer) {
	//	  option (pitaya.method) = { reentrant: true, codec: true };
	//	}
	//
	// optional pitaya.Method method = 50001;
	E_Method = &file_api_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// errors marks an enum as an error code definition.
	// When true, protoc-gen-pitaya-errors generates typed error variables.
	// Usage:
	//
	//	enum ErrorCode {
	//	  option (pitaya.errors) = true;
	//	  ErrOK = 0;
	//	  ErrNotFound = 1001;
	//	}
	//
	// optional bool errors = 50003;
	E_Errors = &file_api_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// error_level specifies the severity level for this error value.
	// Maps to errors.Error.Level field. Default: 0.
	// Usage:
	//
	//	ErrCritical = 2001 [(pitaya.error_level) = 2];
	//
	// optional int32 error_level = 50005;
	E_ErrorLevel = &file_api_annotations_proto_extTypes[3]
)

var File_api_annotations_proto protoreflect.FileDescriptor

const file_api_annotations_proto_rawDesc = "" +
	"\n" +
	"\x15api/annotations.proto\x12\x06pitaya\x1a google/protobuf/descriptor.proto\"T\n" +
	"\x06Method\x12\x1c\n" +
	"\treentrant\x18\x01 \x01(\bR\treentrant\x12\x16\n" +
	"\x06client\x18\x02 \x01(\bR\x06client\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\bR\x05codec:<\n" +
	"\x06domain\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\tR\x06domain\x88\x01\x01:K\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x0e.pitaya.MethodR\x06method\x88\x01\x01:9\n" +
	"\x06errors\x12\x1c.google.protobuf.EnumOptions\x18ӆ\x03 \x01(\bR\x06errors\x88\x01\x01:G\n" +
	"\verror_level\x12!.google.protobuf.EnumValueOptions\x18Ն\x03 \x01(\x05R\n" +
	"errorLevel\x88\x01\x01B)Z'github.com/actfuns/pitaya/v2/protos/apib\x06proto3"

var (
	file_api_annotations_proto_rawDescOnce sync.Once
	file_api_annotations_proto_rawDescData []byte
)

func file_api_annotations_proto_rawDescGZIP() []byte {
	file_api_annotations_proto_rawDescOnce.Do(func() {
		file_api_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_annotations_proto_rawDesc), len(file_api_annotations_proto_rawDesc)))
	})
	return file_api_annotations_proto_rawDescData
}

var file_api_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_annotations_proto_goTypes = []any{
	(*Method)(nil),                        // 0: pitaya.Method
	(*descriptorpb.ServiceOptions)(nil),   // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 2: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 3: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
}
var file_api_annotations_proto_depIdxs = []int32{
	1, // 0: pitaya.domain:extendee -> google.protobuf.ServiceOptions
	2, // 1: pitaya.method:extendee -> google.protobuf.MethodOptions
	3, // 2: pitaya.errors:extendee -> google.protobuf.EnumOptions
	4, // 3: pitaya.error_level:extendee -> google.protobuf.EnumValueOptions
	0, // 4: pitaya.method:type_name -> pitaya.Method
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_annotations_proto_init() }
func file_api_annotations_proto_init() {
	if File_api_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_annotations_proto_rawDesc), len(file_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_api_annotations_proto_goTypes,
		DependencyIndexes: file_api_annotations_proto_depIdxs,
		MessageInfos:      file_api_annotations_proto_msgTypes,
		ExtensionInfos:    file_api_annotations_proto_extTypes,
	}.Build()
	File_api_annotations_proto = out.File
	file_api_annotations_proto_goTypes = nil
	file_api_annotations_proto_depIdxs = nil
}
