// Package prpc provides the core types for pitaya RPC service definitions,
// similar to how google.golang.org/grpc provides ServiceDesc and ServiceRegistrar.
package prpc

import (
	"context"

	"github.com/actfuns/pitaya/v2/component"
)

// Kind enumerates the kinds of services pitaya can register.
// It mirrors the Kind enum in pitaya-protos/api/annotations.proto.
type Kind int32

const (
	// KindHandler registers the service as a client-facing handler service
	// (accessible via WebSocket/TCP).
	KindHandler Kind = 0
	// KindRPC registers the service as a remote service (accessible via RPC).
	KindRPC Kind = 1
)

// MethodDesc describes a single handler/remote method for direct registration.
// Generated by protoc-gen-pitaya.
type MethodDesc struct {
	// MethodName is the method name as used in routes (lowercase first letter).
	MethodName string
	// Handler is the function that calls the service method directly.
	// It receives the service implementation, context, the raw request data,
	// and a prepare function that decodes and runs the pipeline,
	// and returns the result and error.
	Handler func(srv interface{}, ctx context.Context, data []byte, prepare func(ctx context.Context, arg interface{}) (context.Context, interface{}, error)) (interface{}, error)
	// Reentrant indicates this method can be executed concurrently,
	// bypassing the actor serial queue.
	Reentrant bool
	// Codec enables UnmarshalXxx / MarshalXxx hooks for this method.
	Codec bool
}

// ServiceDesc describes a service with its methods for direct registration.
// Modeled after grpc.ServiceDesc.
type ServiceDesc struct {
	// Kind specifies whether this service is a handler or rpc service.
	// Must be KindHandler or KindRPC.
	Kind Kind
	// DomainName is the server type for routing (e.g., "room", "game").
	DomainName string
	// ServiceName is the pitaya service name (lowercase).
	ServiceName string
	// Methods contains all handler/remote method descriptors.
	Methods []MethodDesc
	// HandlerType is a nil pointer to the server interface, used for
	// compile-time type checking (e.g., (*RoomServer)(nil)).
	HandlerType interface{}
}

// ServiceRegistrar is the interface for registering services with pitaya.
// Modeled after grpc.ServiceRegistrar.
type ServiceRegistrar interface {
	Register(desc *ServiceDesc, srv component.Component)
}
