package main

import (
	"flag"
	"fmt"
	"strings"

	protos "github.com/topfreegames/pitaya/v2/protos/api"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "0.1.0"

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-pitaya-errors %v\n", version)
		return
	}

	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range gen.Files {
			if !file.Generate {
				continue
			}

			if !fileHasErrorsEnum(file) {
				continue
			}

			generateFile(gen, file)
		}
		return nil
	})
}

func fileHasErrorsEnum(file *protogen.File) bool {
	for _, enum := range file.Enums {
		if hasErrorsOption(enum) {
			return true
		}
	}
	return false
}

func hasErrorsOption(enum *protogen.Enum) bool {
	opts := enum.Desc.Options()
	if opts == nil {
		return false
	}
	if proto.HasExtension(opts, protos.E_Errors) {
		v := proto.GetExtension(opts, protos.E_Errors)
		if b, ok := v.(bool); ok {
			return b
		}
	}
	return false
}

func readErrorLevel(value *protogen.EnumValue) int32 {
	opts := value.Desc.Options()
	if opts == nil {
		return 0
	}
	if proto.HasExtension(opts, protos.E_ErrorLevel) {
		v := proto.GetExtension(opts, protos.E_ErrorLevel)
		if i, ok := v.(int32); ok {
			return i
		}
	}
	return 0
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	hasErrors := false
	for _, enum := range file.Enums {
		if hasErrorsOption(enum) {
			hasErrors = true
			break
		}
	}
	if !hasErrors {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_errors.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-pitaya-errors. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-pitaya-errors v", version)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import pitayaErr \"github.com/topfreegames/pitaya/v2/errors\"")
	g.P()

	g.P("var (")
	for _, enum := range file.Enums {
		if !hasErrorsOption(enum) {
			continue
		}

		enumName := enum.GoIdent.GoName
		for _, value := range enum.Values {
			name := value.GoIdent.GoName
			name = strings.TrimPrefix(name, enumName+"_")
			code := value.Desc.Number()

			// Extract message from trailing comment
			msg := strings.TrimSpace(value.Comments.Trailing.String())
			if msg == "" {
				msg = strings.TrimSpace(value.Comments.Leading.String())
			}
			msg = strings.TrimPrefix(msg, "//")
			msg = strings.TrimSpace(msg)
			if msg == "" {
				msg = name
			}

			errorLevel := readErrorLevel(value)
			g.P("\t", name, " = &pitayaErr.Error{Code: ", code, ", Level: ", errorLevel, ", Message: \"", msg, "\"}")
		}
	}
	g.P(")")
}
