package main

import (
	"flag"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	protos "github.com/topfreegames/pitaya/v2/protos/api"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "0.1.0"

const (
	contextPackage   = protogen.GoImportPath("context")
	componentPackage = protogen.GoImportPath("github.com/topfreegames/pitaya/v2/component")
	prpcPackage      = protogen.GoImportPath("github.com/topfreegames/pitaya/v2/prpc")
)

const fileDescriptorProtoPackageFieldNumber = 2
const fileDescriptorProtoSyntaxFieldNumber = 12

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-pitaya-prpc %v\n", version)
		return
	}

	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			if !fileHasServicesWithDomain(f) {
				continue
			}

			generateFile(gen, f)
		}
		return nil
	})
}

func fileHasServicesWithDomain(file *protogen.File) bool {
	for _, service := range file.Services {
		if readServiceDomain(service) != "" {
			return true
		}
	}
	return false
}

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_pitaya_prpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	genLeadingComments(g, file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoSyntaxFieldNumber}))
	g.P("// Code generated by protoc-gen-pitaya-prpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-pitaya-prpc v", version)
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	genLeadingComments(g, file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoPackageFieldNumber}))
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g)
	return g
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func generateFileContent(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	for _, service := range file.Services {
		genService(g, service)
	}
}

func genServiceComments(g *protogen.GeneratedFile, service *protogen.Service) {
	if service.Comments.Leading != "" {
		g.P("//")
		g.P(strings.TrimSpace(service.Comments.Leading.String()))
	}
}

func readServiceDomain(service *protogen.Service) string {
	opts := service.Desc.Options().(*descriptorpb.ServiceOptions)
	if opts == nil {
		return ""
	}
	if proto.HasExtension(opts, protos.E_Domain) {
		v := proto.GetExtension(opts, protos.E_Domain)
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

func readMethodClient(method *protogen.Method) bool {
	opts := method.Desc.Options().(*descriptorpb.MethodOptions)
	if opts == nil {
		return false
	}
	if proto.HasExtension(opts, protos.E_Client) {
		v := proto.GetExtension(opts, protos.E_Client)
		if b, ok := v.(bool); ok {
			return b
		}
	}
	return false
}

func readMethodReentrant(method *protogen.Method) bool {
	opts := method.Desc.Options().(*descriptorpb.MethodOptions)
	if opts == nil {
		return false
	}
	if proto.HasExtension(opts, protos.E_Reentrant) {
		v := proto.GetExtension(opts, protos.E_Reentrant)
		if b, ok := v.(bool); ok {
			return b
		}
	}
	return false
}

func genService(g *protogen.GeneratedFile, service *protogen.Service) {
	svcName := service.GoName
	lowerSvc := lowerFirst(string(service.Desc.Name()))
	serviceFullName := string(service.Desc.FullName())
	domain := readServiceDomain(service)

	// Full method name constants
	g.P("const (")
	for _, method := range service.Methods {
		fmSymbol := fmt.Sprintf("PRPC_%s_%s_FullMethodName", svcName, method.GoName)
		fmName := fmt.Sprintf("/%s/%s", serviceFullName, method.Desc.Name())
		g.P(fmSymbol, ` = "`, fmName, `"`)
	}
	g.P(")")
	g.P()

	// Client interface
	prpcClientName := svcName + "PrpcClient"
	g.P("// ", prpcClientName, " is the client API for ", svcName, " service.")
	g.P("type ", prpcClientName, " interface {")
	for _, method := range service.Methods {
		g.P(method.Comments.Leading, clientSignature(g, method))
	}
	g.P("}")
	g.P()

	// Client struct
	g.P("type ", unexport(prpcClientName), " struct {")
	g.P("app ", prpcPackage.Ident("Client"))
	g.P("}")
	g.P()

	// NewClient
	g.P("func New", prpcClientName, "(app ", prpcPackage.Ident("Client"), ") ", prpcClientName, " {")
	g.P("return &", unexport(prpcClientName), "{app: app}")
	g.P("}")
	g.P()

	// Client methods
	for _, method := range service.Methods {
		genClientMethod(g, method, domain, lowerSvc)
	}

	// Server interface
	serverType := svcName + "PrpcServer"
	g.P("// ", serverType, " is the server API for ", svcName, " service.")
	g.P("// All implementations must embed Unimplemented", serverType)
	g.P("// for forward compatibility.")
	genServiceComments(g, service)
	g.AnnotateSymbol(serverType, protogen.Annotation{Location: service.Location})
	g.P("type ", serverType, " interface {")
	g.P(componentPackage.Ident("Component"))
	for _, method := range service.Methods {
		g.AnnotateSymbol(serverType+"."+method.GoName, protogen.Annotation{Location: method.Location})
		g.P(method.Comments.Leading, serverSignature(g, method))
	}
	g.P("}")
	g.P()

	// Unimplemented
	g.P("// Unimplemented", serverType, " must be embedded to have")
	g.P("// forward compatible implementations.")
	g.P("type Unimplemented", serverType, " struct {")
	g.P(componentPackage.Ident("Base"))
	g.P("}")
	g.P()
	for _, method := range service.Methods {
		g.P("func (Unimplemented", serverType, ") ", serverSignature(g, method), "{")
		g.P("return nil, nil")
		g.P("}")
	}
	g.P()

	// Handler functions
	handlerNames := make([]string, 0, len(service.Methods))
	for _, method := range service.Methods {
		hname := genHandlerFunc(g, method, svcName)
		handlerNames = append(handlerNames, hname)
	}
	g.P()

	// ServiceDesc
	descVar := "PRPC_" + svcName + "_ServiceDesc"
	g.P("// ", descVar, " is the ", prpcPackage.Ident("ServiceDesc"), " for ", svcName, " service.")
	g.P("var ", descVar, " = &", prpcPackage.Ident("ServiceDesc"), "{")
	if domain != "" {
		g.P("DomainName: ", strconv.Quote(domain), ",")
	}
	g.P("ServiceName: ", strconv.Quote(lowerSvc), ",")
	g.P("Methods: []", prpcPackage.Ident("MethodDesc"), "{")
	for i := range service.Methods {
		mn := lowerFirst(string(service.Methods[i].Desc.Name()))
		client := readMethodClient(service.Methods[i])
		reentrant := readMethodReentrant(service.Methods[i])
		g.P("{")
		g.P("MethodName: ", strconv.Quote(mn), ",")
		g.P("Handler: ", handlerNames[i], ",")
		g.P("Client: ", strconv.FormatBool(client), ",")
		g.P("Reentrant: ", strconv.FormatBool(reentrant), ",")
		g.P("},")
	}
	g.P("},")
	g.P("}")
	g.P()

	// Register function
	g.P("func Register", svcName, "PrpcServer(s ", prpcPackage.Ident("ServiceRegistrar"), ", srv ", serverType, ") {")
	g.P("s.Register(", descVar, ", srv)")
	g.P("}")
	g.P()
}

func clientSignature(g *protogen.GeneratedFile, method *protogen.Method) string {
	s := method.GoName + "(ctx " + g.QualifiedGoIdent(contextPackage.Ident("Context"))
	s += ", in *" + g.QualifiedGoIdent(method.Input.GoIdent)
	s += ", opts ..." + g.QualifiedGoIdent(prpcPackage.Ident("CallOption"))
	s += ") (*" + g.QualifiedGoIdent(method.Output.GoIdent) + ", error)"
	return s
}

func genClientMethod(g *protogen.GeneratedFile, method *protogen.Method, domain, lowerService string) {
	mn := lowerFirst(string(method.Desc.Name()))
	route := lowerService + "." + mn
	if domain != "" {
		route = domain + "." + lowerService + "." + mn
	}

	g.P("func (c *", unexport(method.Parent.GoName), "PrpcClient) ", clientSignature(g, method), "{")
	g.P("out := new(", method.Output.GoIdent, ")")
	g.P("err := c.app.RPC(ctx, ", strconv.Quote(route), ", out, in, opts...)")
	g.P("if err != nil { return nil, err }")
	g.P("return out, nil")
	g.P("}")
	g.P()
}

func serverSignature(g *protogen.GeneratedFile, method *protogen.Method) string {
	return fmt.Sprintf(
		"%s(%s, %s) (%s, error)",
		method.GoName,
		g.QualifiedGoIdent(contextPackage.Ident("Context")),
		"*"+g.QualifiedGoIdent(method.Input.GoIdent),
		"*"+g.QualifiedGoIdent(method.Output.GoIdent),
	)
}

func genHandlerFunc(g *protogen.GeneratedFile, method *protogen.Method, svcName string) string {
	hname := fmt.Sprintf("_PRPC_%s_%s_Handler", svcName, method.GoName)

	g.P("func ", hname, "(srv interface{}, ctx ", contextPackage.Ident("Context"), ", dec func(ctx ", contextPackage.Ident("Context"), ", arg interface{}) (", contextPackage.Ident("Context"), ", interface{}, error)) (interface{}, error) {")
	g.P("in := new(", method.Input.GoIdent, ")")
	g.P("ctx, result, err := dec(ctx, in)")
	g.P("if err != nil { return nil, err }")
	g.P("return srv.(", svcName, "PrpcServer).", method.GoName, "(ctx, result.(*", method.Input.GoIdent, "))")
	g.P("}")
	return hname
}

func genLeadingComments(g *protogen.GeneratedFile, loc protoreflect.SourceLocation) {
	for _, s := range loc.LeadingDetachedComments {
		g.P(protogen.Comments(s))
		g.P()
	}
	if s := loc.LeadingComments; s != "" {
		g.P(protogen.Comments(s))
		g.P()
	}
}

func unexport(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
