// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/annotations.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "pitaya.domain",
		Tag:           "bytes,50000,opt,name=domain",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "pitaya.reentrant",
		Tag:           "varint,50001,opt,name=reentrant",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "pitaya.client",
		Tag:           "varint,50002,opt,name=client",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "pitaya.errors",
		Tag:           "varint,50003,opt,name=errors",
		Filename:      "api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50005,
		Name:          "pitaya.error_level",
		Tag:           "varint,50005,opt,name=error_level",
		Filename:      "api/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// domain specifies the server type for routing (e.g. "room", "game").
	// Used by protoc-gen-pitaya-prpc to determine the target server type.
	// Usage:
	//
	//	service Room {
	//	  option (pitaya.domain) = "room";
	//	  rpc Join(JoinReq) returns (JoinResp);
	//	}
	//
	// optional string domain = 50000;
	E_Domain = &file_api_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// reentrant marks a method as reentrant (Orleans-style).
	// When true, the method can be executed concurrently without blocking
	// the actor serial queue (e.g., for DB I/O operations).
	// Default: false.
	// Usage:
	//
	//	rpc Query(QueryReq) returns (QueryResp) {
	//	  option (pitaya.reentrant) = true;
	//	}
	//
	// optional bool reentrant = 50001;
	E_Reentrant = &file_api_annotations_proto_extTypes[1]
	// client marks a method as a client-facing handler.
	// When true, the method is registered in both the remote service (for RPC)
	// and the handler service (for direct client connections via WebSocket/TCP).
	// Default: false (only accessible via RPC).
	// Usage:
	//
	//	rpc Join(JoinReq) returns (JoinResp) {
	//	  option (pitaya.client) = true;
	//	}
	//
	// optional bool client = 50002;
	E_Client = &file_api_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// errors marks an enum as an error code definition.
	// When true, protoc-gen-pitaya-errors generates typed error variables.
	// Usage:
	//
	//	enum ErrorCode {
	//	  option (pitaya.errors) = true;
	//	  ErrOK = 0;
	//	  ErrNotFound = 1001;
	//	}
	//
	// optional bool errors = 50003;
	E_Errors = &file_api_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// error_level specifies the severity level for this error value.
	// Maps to errors.Error.Level field. Default: 0.
	// Usage:
	//
	//	ErrCritical = 2001 [(pitaya.error_level) = 2];
	//
	// optional int32 error_level = 50005;
	E_ErrorLevel = &file_api_annotations_proto_extTypes[4]
)

var File_api_annotations_proto protoreflect.FileDescriptor

const file_api_annotations_proto_rawDesc = "" +
	"\n" +
	"\x15api/annotations.proto\x12\x06pitaya\x1a google/protobuf/descriptor.proto:<\n" +
	"\x06domain\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\tR\x06domain\x88\x01\x01:A\n" +
	"\treentrant\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\treentrant\x88\x01\x01:;\n" +
	"\x06client\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\bR\x06client\x88\x01\x01:9\n" +
	"\x06errors\x12\x1c.google.protobuf.EnumOptions\x18ӆ\x03 \x01(\bR\x06errors\x88\x01\x01:G\n" +
	"\verror_level\x12!.google.protobuf.EnumValueOptions\x18Ն\x03 \x01(\x05R\n" +
	"errorLevel\x88\x01\x01B+Z)github.com/topfreegames/pitaya/pkg/protosb\x06proto3"

var file_api_annotations_proto_goTypes = []any{
	(*descriptorpb.ServiceOptions)(nil),   // 0: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 1: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 2: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_api_annotations_proto_depIdxs = []int32{
	0, // 0: pitaya.domain:extendee -> google.protobuf.ServiceOptions
	1, // 1: pitaya.reentrant:extendee -> google.protobuf.MethodOptions
	1, // 2: pitaya.client:extendee -> google.protobuf.MethodOptions
	2, // 3: pitaya.errors:extendee -> google.protobuf.EnumOptions
	3, // 4: pitaya.error_level:extendee -> google.protobuf.EnumValueOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	0, // [0:5] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_annotations_proto_init() }
func file_api_annotations_proto_init() {
	if File_api_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_annotations_proto_rawDesc), len(file_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_api_annotations_proto_goTypes,
		DependencyIndexes: file_api_annotations_proto_depIdxs,
		ExtensionInfos:    file_api_annotations_proto_extTypes,
	}.Build()
	File_api_annotations_proto = out.File
	file_api_annotations_proto_goTypes = nil
	file_api_annotations_proto_depIdxs = nil
}
