// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: kick.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMsg) Reset() {
	*x = KickMsg{}
	mi := &file_kick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMsg) ProtoMessage() {}

func (x *KickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMsg.ProtoReflect.Descriptor instead.
func (*KickMsg) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{0}
}

func (x *KickMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type KickAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kicked        bool                   `protobuf:"varint,1,opt,name=kicked,proto3" json:"kicked"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickAnswer) Reset() {
	*x = KickAnswer{}
	mi := &file_kick_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickAnswer) ProtoMessage() {}

func (x *KickAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_kick_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickAnswer.ProtoReflect.Descriptor instead.
func (*KickAnswer) Descriptor() ([]byte, []int) {
	return file_kick_proto_rawDescGZIP(), []int{1}
}

func (x *KickAnswer) GetKicked() bool {
	if x != nil {
		return x.Kicked
	}
	return false
}

var File_kick_proto protoreflect.FileDescriptor

const file_kick_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"kick.proto\x12\x06protos\"!\n" +
	"\aKickMsg\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"$\n" +
	"\n" +
	"KickAnswer\x12\x16\n" +
	"\x06kicked\x18\x01 \x01(\bR\x06kickedB<Z)github.com/topfreegames/pitaya/pkg/protos\xaa\x02\x0eNPitaya.Protosb\x06proto3"

var (
	file_kick_proto_rawDescOnce sync.Once
	file_kick_proto_rawDescData []byte
)

func file_kick_proto_rawDescGZIP() []byte {
	file_kick_proto_rawDescOnce.Do(func() {
		file_kick_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kick_proto_rawDesc), len(file_kick_proto_rawDesc)))
	})
	return file_kick_proto_rawDescData
}

var file_kick_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kick_proto_goTypes = []any{
	(*KickMsg)(nil),    // 0: protos.KickMsg
	(*KickAnswer)(nil), // 1: protos.KickAnswer
}
var file_kick_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kick_proto_init() }
func file_kick_proto_init() {
	if File_kick_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kick_proto_rawDesc), len(file_kick_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kick_proto_goTypes,
		DependencyIndexes: file_kick_proto_depIdxs,
		MessageInfos:      file_kick_proto_msgTypes,
	}.Build()
	File_kick_proto = out.File
	file_kick_proto_goTypes = nil
	file_kick_proto_depIdxs = nil
}
