// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: pitaya.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pitaya_proto protoreflect.FileDescriptor

const file_pitaya_proto_rawDesc = "" +
	"\n" +
	"\fpitaya.proto\x12\x06protos\x1a\rrequest.proto\x1a\x0eresponse.proto\x1a\n" +
	"push.proto\x1a\n" +
	"bind.proto\x1a\n" +
	"kick.proto2\xd2\x01\n" +
	"\x06Pitaya\x12+\n" +
	"\x04Call\x12\x0f.protos.Request\x1a\x10.protos.Response\"\x00\x12.\n" +
	"\n" +
	"PushToUser\x12\f.protos.Push\x1a\x10.protos.Response\"\x00\x128\n" +
	"\x11SessionBindRemote\x12\x0f.protos.BindMsg\x1a\x10.protos.Response\"\x00\x121\n" +
	"\bKickUser\x12\x0f.protos.KickMsg\x1a\x12.protos.KickAnswer\"\x00B<Z)github.com/topfreegames/pitaya/pkg/protos\xaa\x02\x0eNPitaya.Protosb\x06proto3"

var file_pitaya_proto_goTypes = []any{
	(*Request)(nil),    // 0: protos.Request
	(*Push)(nil),       // 1: protos.Push
	(*BindMsg)(nil),    // 2: protos.BindMsg
	(*KickMsg)(nil),    // 3: protos.KickMsg
	(*Response)(nil),   // 4: protos.Response
	(*KickAnswer)(nil), // 5: protos.KickAnswer
}
var file_pitaya_proto_depIdxs = []int32{
	0, // 0: protos.Pitaya.Call:input_type -> protos.Request
	1, // 1: protos.Pitaya.PushToUser:input_type -> protos.Push
	2, // 2: protos.Pitaya.SessionBindRemote:input_type -> protos.BindMsg
	3, // 3: protos.Pitaya.KickUser:input_type -> protos.KickMsg
	4, // 4: protos.Pitaya.Call:output_type -> protos.Response
	4, // 5: protos.Pitaya.PushToUser:output_type -> protos.Response
	4, // 6: protos.Pitaya.SessionBindRemote:output_type -> protos.Response
	5, // 7: protos.Pitaya.KickUser:output_type -> protos.KickAnswer
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pitaya_proto_init() }
func file_pitaya_proto_init() {
	if File_pitaya_proto != nil {
		return
	}
	file_request_proto_init()
	file_response_proto_init()
	file_push_proto_init()
	file_bind_proto_init()
	file_kick_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pitaya_proto_rawDesc), len(file_pitaya_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pitaya_proto_goTypes,
		DependencyIndexes: file_pitaya_proto_depIdxs,
	}.Build()
	File_pitaya_proto = out.File
	file_pitaya_proto_goTypes = nil
	file_pitaya_proto_depIdxs = nil
}
