// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v2 (interfaces: Pitaya)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	cluster "github.com/topfreegames/pitaya/v2/cluster"
	component "github.com/topfreegames/pitaya/v2/component"
	config "github.com/topfreegames/pitaya/v2/config"
	interfaces "github.com/topfreegames/pitaya/v2/interfaces"
	metrics "github.com/topfreegames/pitaya/v2/metrics"
	router "github.com/topfreegames/pitaya/v2/router"
	"github.com/topfreegames/pitaya/v2/serialize"
	session "github.com/topfreegames/pitaya/v2/session"
	worker "github.com/topfreegames/pitaya/v2/worker"
	proto "google.golang.org/protobuf/proto"
)

// MockPitaya is a mock of Pitaya interface.
type MockPitaya struct {
	ctrl     *gomock.Controller
	recorder *MockPitayaMockRecorder
}

// MockPitayaMockRecorder is the mock recorder for MockPitaya.
type MockPitayaMockRecorder struct {
	mock *MockPitaya
}

// NewMockPitaya creates a new mock instance.
func NewMockPitaya(ctrl *gomock.Controller) *MockPitaya {
	mock := &MockPitaya{ctrl: ctrl}
	mock.recorder = &MockPitayaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (mr *MockPitaya) EXPECT() *MockPitayaMockRecorder {
	return mr.recorder
}

// AddRoute mocks base method.
func (mr *MockPitaya) AddRoute(arg0 string, arg1 router.RoutingFunc) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "AddRoute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoute indicates an expected call of AddRoute.
func (mr *MockPitayaMockRecorder) AddRoute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoute", reflect.TypeOf((*MockPitaya)(nil).AddRoute), arg0, arg1)
}

// Documentation mocks base method.
func (mr *MockPitaya) Documentation(arg0 bool) (map[string]interface{}, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "Documentation", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Documentation indicates an expected call of Documentation.
func (mr *MockPitayaMockRecorder) Documentation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Documentation", reflect.TypeOf((*MockPitaya)(nil).Documentation), arg0)
}

// GetDieChan mocks base method.
func (mr *MockPitaya) GetDieChan() chan bool {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetDieChan")
	ret0, _ := ret[0].(chan bool)
	return ret0
}

// GetDieChan indicates an expected call of GetDieChan.
func (mr *MockPitayaMockRecorder) GetDieChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDieChan", reflect.TypeOf((*MockPitaya)(nil).GetDieChan))
}

// GetMetricsReporters mocks base method.
func (mr *MockPitaya) GetMetricsReporters() []metrics.Reporter {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetMetricsReporters")
	ret0, _ := ret[0].([]metrics.Reporter)
	return ret0
}

// GetMetricsReporters indicates an expected call of GetMetricsReporters.
func (mr *MockPitayaMockRecorder) GetMetricsReporters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsReporters", reflect.TypeOf((*MockPitaya)(nil).GetMetricsReporters))
}

// GetModule mocks base method.
func (mr *MockPitaya) GetModule(arg0 string) (interfaces.Module, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetModule", arg0)
	ret0, _ := ret[0].(interfaces.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModule indicates an expected call of GetModule.
func (mr *MockPitayaMockRecorder) GetModule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModule", reflect.TypeOf((*MockPitaya)(nil).GetModule), arg0)
}

// GetNumberOfConnectedClients mocks base method.
func (mr *MockPitaya) GetNumberOfConnectedClients() int64 {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetNumberOfConnectedClients")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetNumberOfConnectedClients indicates an expected call of GetNumberOfConnectedClients.
func (mr *MockPitayaMockRecorder) GetNumberOfConnectedClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumberOfConnectedClients", reflect.TypeOf((*MockPitaya)(nil).GetNumberOfConnectedClients))
}

// GetServer mocks base method.
func (mr *MockPitaya) GetServer() *cluster.Server {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetServer")
	ret0, _ := ret[0].(*cluster.Server)
	return ret0
}

// GetServer indicates an expected call of GetServer.
func (mr *MockPitayaMockRecorder) GetServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockPitaya)(nil).GetServer))
}

// GetServerByID mocks base method.
func (mr *MockPitaya) GetServerByID(arg0 string) (*cluster.Server, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetServerByID", arg0)
	ret0, _ := ret[0].(*cluster.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerByID indicates an expected call of GetServerByID.
func (mr *MockPitayaMockRecorder) GetServerByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerByID", reflect.TypeOf((*MockPitaya)(nil).GetServerByID), arg0)
}

// GetServerID mocks base method.
func (mr *MockPitaya) GetServerID() string {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetServerID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerID indicates an expected call of GetServerID.
func (mr *MockPitayaMockRecorder) GetServerID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerID", reflect.TypeOf((*MockPitaya)(nil).GetServerID))
}

// GetServers mocks base method.
func (mr *MockPitaya) GetServers() []*cluster.Server {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetServers")
	ret0, _ := ret[0].([]*cluster.Server)
	return ret0
}

// GetServers indicates an expected call of GetServers.
func (mr *MockPitayaMockRecorder) GetServers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServers", reflect.TypeOf((*MockPitaya)(nil).GetServers))
}

// GetServersByType mocks base method.
func (mr *MockPitaya) GetServersByType(arg0 string) (map[string]*cluster.Server, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetServersByType", arg0)
	ret0, _ := ret[0].(map[string]*cluster.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServersByType indicates an expected call of GetServersByType.
func (mr *MockPitayaMockRecorder) GetServersByType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServersByType", reflect.TypeOf((*MockPitaya)(nil).GetServersByType), arg0)
}

// GetSessionFromCtx mocks base method.
func (mr *MockPitaya) GetSessionFromCtx(arg0 context.Context) session.Session {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GetSessionFromCtx", arg0)
	ret0, _ := ret[0].(session.Session)
	return ret0
}

// GetSessionFromCtx indicates an expected call of GetSessionFromCtx.
func (mr *MockPitayaMockRecorder) GetSessionFromCtx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionFromCtx", reflect.TypeOf((*MockPitaya)(nil).GetSessionFromCtx), arg0)
}

// GroupAddMember mocks base method.
func (mr *MockPitaya) GroupAddMember(arg0 context.Context, arg1, arg2 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupAddMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupAddMember indicates an expected call of GroupAddMember.
func (mr *MockPitayaMockRecorder) GroupAddMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupAddMember", reflect.TypeOf((*MockPitaya)(nil).GroupAddMember), arg0, arg1, arg2)
}

// GroupBroadcast mocks base method.
func (mr *MockPitaya) GroupBroadcast(arg0 context.Context, arg1, arg2, arg3 string, arg4 interface{}) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupBroadcast", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupBroadcast indicates an expected call of GroupBroadcast.
func (mr *MockPitayaMockRecorder) GroupBroadcast(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupBroadcast", reflect.TypeOf((*MockPitaya)(nil).GroupBroadcast), arg0, arg1, arg2, arg3, arg4)
}

// GroupContainsMember mocks base method.
func (mr *MockPitaya) GroupContainsMember(arg0 context.Context, arg1, arg2 string) (bool, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupContainsMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupContainsMember indicates an expected call of GroupContainsMember.
func (mr *MockPitayaMockRecorder) GroupContainsMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupContainsMember", reflect.TypeOf((*MockPitaya)(nil).GroupContainsMember), arg0, arg1, arg2)
}

// GroupCountMembers mocks base method.
func (mr *MockPitaya) GroupCountMembers(arg0 context.Context, arg1 string) (int, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupCountMembers", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupCountMembers indicates an expected call of GroupCountMembers.
func (mr *MockPitayaMockRecorder) GroupCountMembers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupCountMembers", reflect.TypeOf((*MockPitaya)(nil).GroupCountMembers), arg0, arg1)
}

// GroupCreate mocks base method.
func (mr *MockPitaya) GroupCreate(arg0 context.Context, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupCreate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupCreate indicates an expected call of GroupCreate.
func (mr *MockPitayaMockRecorder) GroupCreate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupCreate", reflect.TypeOf((*MockPitaya)(nil).GroupCreate), arg0, arg1)
}

// GroupCreateWithTTL mocks base method.
func (mr *MockPitaya) GroupCreateWithTTL(arg0 context.Context, arg1 string, arg2 time.Duration) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupCreateWithTTL", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupCreateWithTTL indicates an expected call of GroupCreateWithTTL.
func (mr *MockPitayaMockRecorder) GroupCreateWithTTL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupCreateWithTTL", reflect.TypeOf((*MockPitaya)(nil).GroupCreateWithTTL), arg0, arg1, arg2)
}

// GroupDelete mocks base method.
func (mr *MockPitaya) GroupDelete(arg0 context.Context, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupDelete indicates an expected call of GroupDelete.
func (mr *MockPitayaMockRecorder) GroupDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupDelete", reflect.TypeOf((*MockPitaya)(nil).GroupDelete), arg0, arg1)
}

// GroupMembers mocks base method.
func (mr *MockPitaya) GroupMembers(arg0 context.Context, arg1 string) ([]string, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupMembers", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupMembers indicates an expected call of GroupMembers.
func (mr *MockPitayaMockRecorder) GroupMembers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupMembers", reflect.TypeOf((*MockPitaya)(nil).GroupMembers), arg0, arg1)
}

// GroupRemoveAll mocks base method.
func (mr *MockPitaya) GroupRemoveAll(arg0 context.Context, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupRemoveAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupRemoveAll indicates an expected call of GroupRemoveAll.
func (mr *MockPitayaMockRecorder) GroupRemoveAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupRemoveAll", reflect.TypeOf((*MockPitaya)(nil).GroupRemoveAll), arg0, arg1)
}

// GroupRemoveMember mocks base method.
func (mr *MockPitaya) GroupRemoveMember(arg0 context.Context, arg1, arg2 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupRemoveMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupRemoveMember indicates an expected call of GroupRemoveMember.
func (mr *MockPitayaMockRecorder) GroupRemoveMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupRemoveMember", reflect.TypeOf((*MockPitaya)(nil).GroupRemoveMember), arg0, arg1, arg2)
}

// GroupRenewTTL mocks base method.
func (mr *MockPitaya) GroupRenewTTL(arg0 context.Context, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "GroupRenewTTL", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GroupRenewTTL indicates an expected call of GroupRenewTTL.
func (mr *MockPitayaMockRecorder) GroupRenewTTL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupRenewTTL", reflect.TypeOf((*MockPitaya)(nil).GroupRenewTTL), arg0, arg1)
}

// IsRunning mocks base method.
func (mr *MockPitaya) IsRunning() bool {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockPitayaMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockPitaya)(nil).IsRunning))
}

// RPC mocks base method.
func (mr *MockPitaya) RPC(arg0 context.Context, arg1 string, arg2, arg3 proto.Message) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "RPC", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RPC indicates an expected call of RPC.
func (mr *MockPitayaMockRecorder) RPC(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPC", reflect.TypeOf((*MockPitaya)(nil).RPC), arg0, arg1, arg2, arg3)
}

// RPCTo mocks base method.
func (mr *MockPitaya) RPCTo(arg0 context.Context, arg1, arg2 string, arg3, arg4 proto.Message) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "RPCTo", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// RPCTo indicates an expected call of RPCTo.
func (mr *MockPitayaMockRecorder) RPCTo(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPCTo", reflect.TypeOf((*MockPitaya)(nil).RPCTo), arg0, arg1, arg2, arg3, arg4)
}

// Register mocks base method.
func (mr *MockPitaya) Register(arg0 component.Component, arg1 ...component.Option) {
	mr.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	mr.ctrl.Call(mr, "Register", varargs...)
}

// Register indicates an expected call of Register.
func (mr *MockPitayaMockRecorder) Register(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockPitaya)(nil).Register), varargs...)
}

// RegisterModule mocks base method.
func (mr *MockPitaya) RegisterModule(arg0 interfaces.Module, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "RegisterModule", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterModule indicates an expected call of RegisterModule.
func (mr *MockPitayaMockRecorder) RegisterModule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterModule", reflect.TypeOf((*MockPitaya)(nil).RegisterModule), arg0, arg1)
}

// RegisterModuleAfter mocks base method.
func (mr *MockPitaya) RegisterModuleAfter(arg0 interfaces.Module, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "RegisterModuleAfter", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterModuleAfter indicates an expected call of RegisterModuleAfter.
func (mr *MockPitayaMockRecorder) RegisterModuleAfter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterModuleAfter", reflect.TypeOf((*MockPitaya)(nil).RegisterModuleAfter), arg0, arg1)
}

// RegisterModuleBefore mocks base method.
func (mr *MockPitaya) RegisterModuleBefore(arg0 interfaces.Module, arg1 string) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "RegisterModuleBefore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterModuleBefore indicates an expected call of RegisterModuleBefore.
func (mr *MockPitayaMockRecorder) RegisterModuleBefore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterModuleBefore", reflect.TypeOf((*MockPitaya)(nil).RegisterModuleBefore), arg0, arg1)
}

// RegisterRPCJob mocks base method.
func (mr *MockPitaya) RegisterRPCJob(arg0 worker.RPCJob) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "RegisterRPCJob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterRPCJob indicates an expected call of RegisterRPCJob.
func (mr *MockPitayaMockRecorder) RegisterRPCJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRPCJob", reflect.TypeOf((*MockPitaya)(nil).RegisterRPCJob), arg0)
}

// RegisterRemote mocks base method.
func (mr *MockPitaya) RegisterRemote(arg0 component.Component, arg1 ...component.Option) {
	mr.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	mr.ctrl.Call(mr, "RegisterRemote", varargs...)
}

// RegisterRemote indicates an expected call of RegisterRemote.
func (mr *MockPitayaMockRecorder) RegisterRemote(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRemote", reflect.TypeOf((*MockPitaya)(nil).RegisterRemote), varargs...)
}

// ReliableRPC mocks base method.
func (mr *MockPitaya) ReliableRPC(arg0 string, arg1 map[string]interface{}, arg2, arg3 proto.Message) (string, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "ReliableRPC", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReliableRPC indicates an expected call of ReliableRPC.
func (mr *MockPitayaMockRecorder) ReliableRPC(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReliableRPC", reflect.TypeOf((*MockPitaya)(nil).ReliableRPC), arg0, arg1, arg2, arg3)
}

// ReliableRPCWithOptions mocks base method.
func (mr *MockPitaya) ReliableRPCWithOptions(arg0 string, arg1 map[string]interface{}, arg2, arg3 proto.Message, arg4 *config.EnqueueOpts) (string, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "ReliableRPCWithOptions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReliableRPCWithOptions indicates an expected call of ReliableRPCWithOptions.
func (mr *MockPitayaMockRecorder) ReliableRPCWithOptions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReliableRPCWithOptions", reflect.TypeOf((*MockPitaya)(nil).ReliableRPCWithOptions), arg0, arg1, arg2, arg3, arg4)
}

// SendKickToUsers mocks base method.
func (mr *MockPitaya) SendKickToUsers(arg0 []string, arg1 string) ([]string, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "SendKickToUsers", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendKickToUsers indicates an expected call of SendKickToUsers.
func (mr *MockPitayaMockRecorder) SendKickToUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendKickToUsers", reflect.TypeOf((*MockPitaya)(nil).SendKickToUsers), arg0, arg1)
}

// SendPushToUsers mocks base method.
func (mr *MockPitaya) SendPushToUsers(arg0 string, arg1 interface{}, arg2 []string, arg3 string) ([]string, error) {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "SendPushToUsers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPushToUsers indicates an expected call of SendPushToUsers.
func (mr *MockPitayaMockRecorder) SendPushToUsers(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPushToUsers", reflect.TypeOf((*MockPitaya)(nil).SendPushToUsers), arg0, arg1, arg2, arg3)
}

// SetDebug mocks base method.
func (mr *MockPitaya) SetDebug(arg0 bool) {
	mr.ctrl.T.Helper()
	mr.ctrl.Call(mr, "SetDebug", arg0)
}

// SetDebug indicates an expected call of SetDebug.
func (mr *MockPitayaMockRecorder) SetDebug(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDebug", reflect.TypeOf((*MockPitaya)(nil).SetDebug), arg0)
}

// SetDictionary mocks base method.
func (mr *MockPitaya) SetDictionary(arg0 map[string]uint16) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "SetDictionary", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDictionary indicates an expected call of SetDictionary.
func (mr *MockPitayaMockRecorder) SetDictionary(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDictionary", reflect.TypeOf((*MockPitaya)(nil).SetDictionary), arg0)
}

// SetHeartbeatTime mocks base method.
func (mr *MockPitaya) SetHeartbeatTime(arg0 time.Duration) {
	mr.ctrl.T.Helper()
	mr.ctrl.Call(mr, "SetHeartbeatTime", arg0)
}

// SetHeartbeatTime indicates an expected call of SetHeartbeatTime.
func (mr *MockPitayaMockRecorder) SetHeartbeatTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeartbeatTime", reflect.TypeOf((*MockPitaya)(nil).SetHeartbeatTime), arg0)
}

// Shutdown mocks base method.
func (mr *MockPitaya) Shutdown() {
	mr.ctrl.T.Helper()
	mr.ctrl.Call(mr, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockPitayaMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockPitaya)(nil).Shutdown))
}

// Start mocks base method.
func (mr *MockPitaya) Start() {
	mr.ctrl.T.Helper()
	mr.ctrl.Call(mr, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockPitayaMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPitaya)(nil).Start))
}

// StartWorker mocks base method.
func (mr *MockPitaya) StartWorker() {
	mr.ctrl.T.Helper()
	mr.ctrl.Call(mr, "StartWorker")
}

// StartWorker indicates an expected call of StartWorker.
func (mr *MockPitayaMockRecorder) StartWorker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWorker", reflect.TypeOf((*MockPitaya)(nil).StartWorker))
}

// SubmitTask mocks base method.
func (mr *MockPitaya) SubmitTask(arg0 context.Context, arg1 string, arg2 func(context.Context)) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "SubmitTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitTask indicates an expected call of SubmitTask.
func (mr *MockPitayaMockRecorder) SubmitTask(arg0 context.Context, arg1 string, arg2 func(context.Context)) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitTask", reflect.TypeOf((*MockPitaya)(nil).SubmitTask), arg0, arg1, arg2)
}

// SubmitAnonymousTask mocks base method.
func (mr *MockPitaya) SubmitAnonymousTask(arg0 context.Context, arg1 func(context.Context)) error {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "SubmitAnonymousTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitAnonymousTask indicates an expected call of SubmitAnonymousTask.
func (mr *MockPitayaMockRecorder) SubmitAnonymousTask(arg0 context.Context, arg1 func(context.Context)) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAnonymousTask", reflect.TypeOf((*MockPitaya)(nil).SubmitAnonymousTask), arg0, arg1)
}

// SetInterval mocks base method.
func (m *MockPitaya) SetInterval(arg0 string, arg1 time.Duration, arg2 int, arg3 func(context.Context)) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInterval", arg0, arg1, arg2, arg3)

	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// SetInterval indicates an expected call of SetInterval.
func (mr *MockPitayaMockRecorder) SetInterval(arg0 string, arg1 time.Duration, arg2 int, arg3 func(context.Context)) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInterval", reflect.TypeOf((*MockPitaya)(nil).SetInterval), arg0, arg1, arg2, arg3)
}

// ClearInterval mocks base method.
func (m *MockPitaya) ClearInterval(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearInterval", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearInterval indicates an expected call of ClearInterval.
func (mr *MockPitayaMockRecorder) ClearInterval(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"ClearInterval",
		reflect.TypeOf((*MockPitaya)(nil).ClearInterval),
		arg0,
	)
}

// UpdateServerMetadata mocks base method.
func (m *MockPitaya) UpdateServerMetadata(arg0 map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServerMetadata", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServerMetadata indicates an expected call of UpdateServerMetadata.
func (mr *MockPitayaMockRecorder) UpdateServerMetadata(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"UpdateServerMetadata",
		reflect.TypeOf((*MockPitaya)(nil).UpdateServerMetadata),
		arg0,
	)
}

// GetSerializer mocks base method.
func (m *MockPitaya) GetSerializer() serialize.Serializer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSerializer")
	ret0, _ := ret[0].(serialize.Serializer)
	return ret0
}

// GetSerializer indicates an expected call of GetSerializer.
func (mr *MockPitayaMockRecorder) GetSerializer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"GetSerializer",
		reflect.TypeOf((*MockPitaya)(nil).GetSerializer),
	)
}

// RPCHandle mocks base method.
func (m *MockPitaya) RPCHandle(arg0 context.Context, arg1 string, arg2 proto.Message, arg3 proto.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPCHandle", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RPCHandle indicates an expected call of RPCHandle.
func (mr *MockPitayaMockRecorder) RPCHandle(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"RPCHandle",
		reflect.TypeOf((*MockPitaya)(nil).RPCHandle),
		arg0,
		arg1,
		arg2,
		arg3,
	)
}

// RPCHandleTo mocks base method.
func (m *MockPitaya) RPCHandleTo(arg0 context.Context, arg1 string, arg2 string, arg3 proto.Message, arg4 proto.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPCHandleTo", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// RPCHandleTo indicates an expected call of RPCHandleTo.
func (mr *MockPitayaMockRecorder) RPCHandleTo(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"RPCHandleTo",
		reflect.TypeOf((*MockPitaya)(nil).RPCHandleTo),
		arg0,
		arg1,
		arg2,
		arg3,
		arg4,
	)
}

// SetDispatch mocks base method.
func (m *MockPitaya) SetDispatch(arg0 router.DispatchFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDispatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDispatch indicates an expected call of SetDispatch.
func (mr *MockPitayaMockRecorder) SetDispatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SetDispatch",
		reflect.TypeOf((*MockPitaya)(nil).SetDispatch),
		arg0,
	)
}

// IsReady mocks base method.
func (mr *MockPitaya) IsReady(arg0 context.Context) bool {
	mr.ctrl.T.Helper()
	ret := mr.ctrl.Call(mr, "IsReady", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady.
func (mr *MockPitayaMockRecorder) IsReady(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockPitaya)(nil).IsReady), arg0)
}
