// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/actfuns/pitaya/v2/metrics (interfaces: Reporter)
//
// Generated by this command:
//
//	mockgen github.com/actfuns/pitaya/v2/metrics Reporter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// ReportCount mocks base method.
func (m *MockReporter) ReportCount(metric string, tags map[string]string, count float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportCount", metric, tags, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportCount indicates an expected call of ReportCount.
func (mr *MockReporterMockRecorder) ReportCount(metric, tags, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCount", reflect.TypeOf((*MockReporter)(nil).ReportCount), metric, tags, count)
}

// ReportGauge mocks base method.
func (m *MockReporter) ReportGauge(metric string, tags map[string]string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportGauge", metric, tags, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportGauge indicates an expected call of ReportGauge.
func (mr *MockReporterMockRecorder) ReportGauge(metric, tags, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportGauge", reflect.TypeOf((*MockReporter)(nil).ReportGauge), metric, tags, value)
}

// ReportHistogram mocks base method.
func (m *MockReporter) ReportHistogram(metric string, tags map[string]string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportHistogram", metric, tags, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportHistogram indicates an expected call of ReportHistogram.
func (mr *MockReporterMockRecorder) ReportHistogram(metric, tags, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportHistogram", reflect.TypeOf((*MockReporter)(nil).ReportHistogram), metric, tags, value)
}

// ReportSummary mocks base method.
func (m *MockReporter) ReportSummary(metric string, tags map[string]string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportSummary", metric, tags, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportSummary indicates an expected call of ReportSummary.
func (mr *MockReporterMockRecorder) ReportSummary(metric, tags, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportSummary", reflect.TypeOf((*MockReporter)(nil).ReportSummary), metric, tags, value)
}
