syntax = "proto3";

package protos.service;
option go_package = "github.com/actfuns/pitaya/v2/protos/service";

import "response.proto";
import "kick.proto";
import "session.proto";
import "api/annotations.proto";

service Sys {
  option (pitaya.domain) = "sys";

  rpc BindSession(Session) returns (Response) {
    option (pitaya.reentrant) = true;
  }

  rpc PushSession(Session) returns (Response) {
    option (pitaya.reentrant) = true;
  }

  rpc Kick(KickMsg) returns (KickAnswer) {
    option (pitaya.reentrant) = true;
  }
}
